import { useNavigate } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

function TermsPage() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="flex items-center gap-3 px-4 py-4 bg-white border-b border-gray-100 sticky top-0 z-10">
        <button
          onClick={() => navigate(-1)}
          aria-label="Go back"
          className="text-gray-500 hover:text-gray-700"
        >
          <ArrowLeft size={22} />
        </button>
        <h1 className="font-bold text-gray-800 text-lg">
          Terms and Conditions
        </h1>
      </div>

      <div className="max-w-2xl mx-auto px-4 py-8 prose prose-sm text-gray-700">
        <p className="text-sm text-gray-400 mb-8">
          Last updated April 08, 2026
        </p>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            1. Agreement to Terms
          </h2>
          <p>
            These Terms and Conditions constitute a legally binding agreement
            between you and IngredientIQ ("we," "us," or "our") governing your
            access to and use of the IngredientIQ web application and mobile PWA
            ("the App"). By accessing or using the App, you confirm that you
            have read, understood, and agree to be bound by these Terms. If you
            do not agree, please discontinue use immediately.
          </p>
          <p className="mt-3">
            IngredientIQ is a smart food safety scanner that uses optical
            character recognition and artificial intelligence to analyse
            ingredient labels on packaged food products. Results are for
            informational purposes only and do not constitute medical, dietary,
            or nutritional advice.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            2. Eligibility
          </h2>
          <p>
            You must be at least 18 years of age to use IngredientIQ. By using
            the App, you represent and warrant that you are 18 years of age or
            older. If you are under 18, you are not permitted to use the App.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            3. User Accounts
          </h2>
          <p>
            You may use the core scanning features of IngredientIQ without
            creating an account. To access scan history and personalised
            features, you must register for an account. You are responsible for
            maintaining the confidentiality of your account credentials and for
            all activity that occurs under your account. You agree to notify us
            immediately of any unauthorised use of your account.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            4. AI-Generated Analysis Disclaimer
          </h2>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-3">
            <p className="font-semibold text-amber-800 mb-2">
              Important Notice
            </p>
            <p className="text-amber-700">
              The ingredient safety analysis provided by IngredientIQ is
              generated by artificial intelligence and is intended for
              informational purposes only. It does not constitute medical,
              dietary, or nutritional advice and should not be relied upon as a
              substitute for professional medical guidance. IngredientIQ makes
              no warranties regarding the accuracy, completeness, or reliability
              of any AI-generated analysis. By using this service, you
              acknowledge that results may not be accurate and agree not to make
              health or dietary decisions based solely on the analysis provided.
            </p>
          </div>
          <p>
            Users with specific dietary requirements, allergies, or health
            conditions must consult a qualified healthcare professional before
            making food choices based on this App.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            5. Prohibited Activities
          </h2>
          <p className="mb-3">You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              Use the App to advertise or offer to sell goods and services
            </li>
            <li>Sell or otherwise transfer your profile or account</li>
            <li>
              Use the AI-generated ingredient analysis for medical diagnosis or
              as a substitute for professional medical advice
            </li>
            <li>
              Attempt to reverse engineer, hack, or disrupt the App or its
              services
            </li>
            <li>Use automated scripts or bots to access the App</li>
            <li>
              Violate any applicable local, national, or international laws or
              regulations
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            6. Intellectual Property
          </h2>
          <p>
            The App, its original content, features, and functionality are and
            will remain the exclusive property of IngredientIQ. The App is
            protected by copyright and other intellectual property laws. You may
            not reproduce, distribute, or create derivative works without our
            express written permission.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            7. Third-Party Services
          </h2>
          <p>
            IngredientIQ uses third-party services including Google Generative
            AI (Gemini), Supabase, Vercel, Render, and Resend to operate. We are
            not responsible for the availability, accuracy, or content of these
            third-party services. Your use of third-party services is governed
            by their respective terms and privacy policies.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            8. Limitation of Liability
          </h2>
          <p>
            To the fullest extent permitted by applicable law, IngredientIQ
            shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages arising from your use of the App.
            Our total liability to you for any claims arising from your use of
            the App shall not exceed the amount you paid us in the twelve months
            prior to the claim — which, as the App is free, is zero.
          </p>
          <p className="mt-3">
            We do not warrant that the App will be uninterrupted, error-free, or
            free of viruses or other harmful components.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">9. Privacy</h2>
          <p>
            Your use of the App is also governed by our{' '}
            <a href="/privacy" className="text-green-600 hover:underline">
              Privacy Policy
            </a>
            , which is incorporated into these Terms by reference.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            10. Termination
          </h2>
          <p>
            We reserve the right to suspend or terminate your access to the App
            at our sole discretion, without notice, for conduct that we believe
            violates these Terms or is harmful to other users, us, or third
            parties. You may terminate your account at any time from the Profile
            page in the App.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            11. Dispute Resolution
          </h2>
          <p>
            In the event of any dispute arising out of or relating to these
            Terms or the App, the parties agree to first attempt to resolve the
            dispute through informal negotiations for a period of 30 days. If
            the dispute cannot be resolved informally, it shall be submitted to
            binding arbitration in Dublin, Ireland, conducted in English.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            12. Governing Law
          </h2>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of Ireland, without regard to its conflict of law
            provisions. Any disputes not resolved by arbitration shall be
            subject to the exclusive jurisdiction of the courts of Dublin,
            Ireland.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            13. Changes to Terms
          </h2>
          <p>
            We reserve the right to update these Terms at any time. We will
            notify you of significant changes by posting a notice in the App at
            least 7 days before the changes take effect. Your continued use of
            the App after changes are posted constitutes your acceptance of the
            updated Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-3">
            14. Contact Us
          </h2>
          <p>
            If you have any questions about these Terms, please contact us at:
          </p>
          <div className="mt-3 p-4 bg-gray-100 rounded-xl text-sm">
            <p>
              <strong>IngredientIQ</strong>
            </p>
            <p>Dublin, Ireland</p>
            <p>
              Email:{' '}
              <a
                href="mailto:alabaoreoluwa@gmail.com"
                className="text-green-600 hover:underline"
              >
                alabaoreoluwa@gmail.com
              </a>
            </p>
          </div>
        </section>
      </div>
    </div>
  )
}

export default TermsPage
